### ISSUE TITLE
Cannot import muon: AttributeError: module 'anndata.compat' has no attribute 'Literal'

### ISSUE THREAD

**Issue by havu73** [scverse/muon#102]
Hi, I have Anndata version 0.9.1.  I have been trying to install muon so that I can also process multiome data. However, whenever I tried to install Muon I always encounter the error message: 
```
Python 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:45:29) 
[GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import anndata
>>> import muon as mu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u/home/h/havu73/project-ernst/anaconda/envs/sc_env/lib/python3.9/site-packages/muon/__init__.py", line 3, in <module>
    from mudata import MuData
  File "/u/home/h/havu73/project-ernst/anaconda/envs/sc_env/lib/python3.9/site-packages/mudata/__init__.py", line 3, in <module>
    from ._core.mudata import MuData
  File "/u/home/h/havu73/project-ernst/anaconda/envs/sc_env/lib/python3.9/site-packages/mudata/_core/mudata.py", line 30, in <module>
    from .file_backing import MuDataFileManager
  File "/u/home/h/havu73/project-ernst/anaconda/envs/sc_env/lib/python3.9/site-packages/mudata/_core/file_backing.py", line 13, in <module>
    class MuDataFileManager(AnnDataFileManager):
  File "/u/home/h/havu73/project-ernst/anaconda/envs/sc_env/lib/python3.9/site-packages/mudata/_core/file_backing.py", line 17, in MuDataFileManager
    filemode: Optional[ad.compat.Literal["r", "r+"]] = None,
AttributeError: module 'anndata.compat' has no attribute 'Literal'
>>> 
```

I installed Anndata using conda and muon using pip. Can you help me trouble shoot this please?

Thank you so much!

Sincerely,
Ha T Vu

**Comment by gtca** [comment]
Hey @havu73,

The latest `anndata 0.9.1` and `muon 0.1.3` should work together fine:

```py
import anndata
anndata.__version__  # => '0.9.1'

import muon as mu
muon.__version__  # =>'0.1.3'
```

And `muon` on PyPI is `0.1.3` at the moment so there should be no problem. How recent is this issue?

**Comment by havu73** [comment]
Hi! Thank you so much for your response! I really appreciate it! I ended up reinstalling my anaconda and redo all installation again. Now, the two packages work! Thank you so much!

**Comment by AaronNing** [comment]
> Hey @havu73,
> 
> The latest `anndata 0.9.1` and `muon 0.1.3` should work together fine:
> 
> ```python
> import anndata
> anndata.__version__  # => '0.9.1'
> 
> import muon as mu
> mu.__version__  # =>'0.1.3'
> ```
> 
> And `muon` on PyPI is `0.1.3` at the moment so there should be no problem. How recent is this issue?

For later users, I'd add that `mudata==0.2.1` raises this error even when `muon==0.1.3` and `anndata==0.9.1`. Updating to `mudata==0.2.3` solved the problem.
