### ISSUE TITLE
`python setup.py egg_info did not run successfully.` during install

### ISSUE THREAD

**Issue by danli349** [scverse/muon#83]
Hello

When I install `muon`:
```
~$ python -m pip install muon
```
I got this error:
```
Collecting muon
  Using cached muon-0.1.2-py3-none-any.whl (287 kB)
Requirement already satisfied: pandas in ./miniconda3/lib/python3.8/site-packages (from muon) (1.4.4)
Requirement already satisfied: numpy in ./miniconda3/lib/python3.8/site-packages (from muon) (1.23.4)
Collecting loompy
  Downloading loompy-3.0.7.tar.gz (4.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 30.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-qixwjllu/loompy_140512fbbeff4df183a31339573cf60b/setup.py", line 16, in <module>
          setup(
        File "/home/dan/miniconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/dan/miniconda3/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/home/dan/miniconda3/lib/python3.8/site-packages/setuptools/dist.py", line 475, in __init__
          _Distribution.__init__(
        File "/home/dan/miniconda3/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/home/dan/miniconda3/lib/python3.8/site-packages/setuptools/dist.py", line 898, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/home/dan/miniconda3/lib/python3.8/site-packages/setuptools/dist.py", line 897, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/home/dan/miniconda3/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
          module = import_module(match.group('module'))
        File "/home/dan/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
        File "<frozen importlib._bootstrap>", line 991, in _find_and_load
        File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
      ModuleNotFoundError: No module named 'setuptools_scm.integration'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Can you please help me to fix it?
Thanks a lot.

**Comment by danli349** [comment]
I fix this error by  `python -m pip install setuptools-scm`. Thanks
